{
    "name": "Arkana - Custom CRM Leads",
    "summary": "Custom CRM Leads",
    "version": "14.0.1.0.0",
    "category": "Others",
    "author": "Nur Kholid",
    "maintainers": ["nrkholid"],
    "website": "https://arkana.co.id",
    "license": "AGPL-3",
    "depends": ["base", "contacts", "crm", "crm_enterprise", "sales_team",
                "sale", "sale_crm", "product", "stock"],
    "data": [
        "security/ir.model.access.csv",
        "data/partner_setup_data.xml",
        "data/crm_setup_data.xml",
        "views/partner_setup_view.xml",
        "views/crm_setup_view.xml",
        "views/res_partner_view_inherit.xml",
        "views/product_view_inherit.xml",
        "views/crm_lost_reason_view_inherit.xml",
        "views/crm_lead_view_inherit.xml",
        "views/crm_lead_reporting_view.xml",
        "views/crm_menu_root_view.xml",
    ],
    "auto_install": False,
    "installable": True,
    "application": True,
    "external_dependencies": {"python": []},
}
