{
    'name': 'Payroll Indonesia Enterprise Edition',
    'version': '14.0.1.0.1',
    'summary': 'BPJS, pph21, BPJS Tenaker, Input Extra Insentif, Input Extra Deduction, Konfigurasi aturan pph 21, cutoff period, SPT masa pph, 1721, 1721-A1, Bank List',
    'author': 'odoohris.com',
    'description': 'Addons untuk perhitungan payroll indonesia yang meliputi perhitungan BPJS Kesehatan, BPJS Ketenagakerjaan (JKK,JKM,JHT,JP), PPH21 (Nett, Gross, Grossup)',
    'price' : 600,
    'currency' : 'USD',
    'company': 'Odoo HRIS',
    'website': 'https://odoohris.com',
    'depends': ['base','hr','hr_payroll','hr_contract','hr_work_entry_contract'],
    'data': [
        #wizard
        'views/wizard/report_payroll_wizard.xml',
        'views/report/pph21_i.xml',
        #report
        'views/report/print_payslip.xml',
        #views
        'views/config_view.xml',
        'views/employee.xml',
        'views/cutoff_periode.xml',
        'views/hr_pinjaman.xml',
        'views/limit_settings.xml',
        'views/contract.xml',
        'views/input_extra.xml',
        'views/hr_salary_rule.xml',
        'views/hr_payslips.xml',
        'views/payslip_run.xml',
        'views/master_ump.xml',
        'views/lapis_pph.xml',
        'security/ir.model.access.csv',
        #data
        # 'data/cutoff.periode.csv',
        # 'data/hr.ptkp.csv',
        # 'data/hr.limit.bpjs.ks.csv',
        # 'data/hr.limit.jp.csv',
        # 'data/hr.jkktabel.csv',
        # 'data/hr.limit.bijab.csv',
        # 'data/hr.master.ump.csv',
        # 'data/hr.lapis.pph.csv',
        # 'data/hr.contract.basecomponent.csv',
    ],
    'category': 'Generic Modules/Human Resources',
    'maintainer': 'odoohris',
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'OPL-1',
    'support': '',
    'images': ['static/description/banner.jpg'],
}